/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-generated-swagger-docs.sh

// AUTO-GENERATED FUNCTIONS START HERE. DO NOT EDIT.
var map_ClusterSpec = map[string]string{
	"": "ClusterSpec contains service configuration mapped to a specific cluster",
}

func (ClusterSpec) SwaggerDoc() map[string]string {
	return map_ClusterSpec
}

var map_ServiceExport = map[string]string{
	"": "ServiceExport declares that the associated service should be exported to other clusters.",
}

func (ServiceExport) SwaggerDoc() map[string]string {
	return map_ServiceExport
}

var map_ServiceExportCondition = map[string]string{
	"":       "ServiceExportCondition contains details for the current condition of this service export.\n\nOnce [#1624](https://github.com/kubernetes/enhancements/pull/1624) is merged, this will be replaced by metav1.Condition.",
	"status": "Status is one of {\"True\", \"False\", \"Unknown\"}",
}

func (ServiceExportCondition) SwaggerDoc() map[string]string {
	return map_ServiceExportCondition
}

var map_ServiceExportList = map[string]string{
	"":         "ServiceExportList represents a list of endpoint slices",
	"metadata": "Standard list metadata.",
	"items":    "List of endpoint slices",
}

func (ServiceExportList) SwaggerDoc() map[string]string {
	return map_ServiceExportList
}

var map_ServiceExportStatus = map[string]string{
	"": "ServiceExportStatus contains the current status of an export.",
}

func (ServiceExportStatus) SwaggerDoc() map[string]string {
	return map_ServiceExportStatus
}

var map_ServiceImport = map[string]string{
	"": "ServiceImport declares that the specified service should be exported to other clusters.",
}

func (ServiceImport) SwaggerDoc() map[string]string {
	return map_ServiceImport
}

var map_ServiceImportList = map[string]string{
	"":         "ServiceImportList represents a list of endpoint slices",
	"metadata": "Standard list metadata.",
	"items":    "List of endpoint slices",
}

func (ServiceImportList) SwaggerDoc() map[string]string {
	return map_ServiceImportList
}

var map_ServiceImportSpec = map[string]string{
	"": "ServiceImportSpec contains the current status of an imported service and the information necessary to consume it",
}

func (ServiceImportSpec) SwaggerDoc() map[string]string {
	return map_ServiceImportSpec
}

// AUTO-GENERATED FUNCTIONS END HERE
