// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1 "k8s.io/api/core/v1"
	v1alpha1 "k8s.io/api/multicluster/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	core "k8s.io/kubernetes/pkg/apis/core"
	multicluster "k8s.io/kubernetes/pkg/apis/multicluster"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ClusterSpec)(nil), (*multicluster.ClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterSpec_To_multicluster_ClusterSpec(a.(*v1alpha1.ClusterSpec), b.(*multicluster.ClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*multicluster.ClusterSpec)(nil), (*v1alpha1.ClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_multicluster_ClusterSpec_To_v1alpha1_ClusterSpec(a.(*multicluster.ClusterSpec), b.(*v1alpha1.ClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ServiceExport)(nil), (*multicluster.ServiceExport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServiceExport_To_multicluster_ServiceExport(a.(*v1alpha1.ServiceExport), b.(*multicluster.ServiceExport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*multicluster.ServiceExport)(nil), (*v1alpha1.ServiceExport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_multicluster_ServiceExport_To_v1alpha1_ServiceExport(a.(*multicluster.ServiceExport), b.(*v1alpha1.ServiceExport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ServiceExportCondition)(nil), (*multicluster.ServiceExportCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServiceExportCondition_To_multicluster_ServiceExportCondition(a.(*v1alpha1.ServiceExportCondition), b.(*multicluster.ServiceExportCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*multicluster.ServiceExportCondition)(nil), (*v1alpha1.ServiceExportCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_multicluster_ServiceExportCondition_To_v1alpha1_ServiceExportCondition(a.(*multicluster.ServiceExportCondition), b.(*v1alpha1.ServiceExportCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ServiceExportList)(nil), (*multicluster.ServiceExportList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServiceExportList_To_multicluster_ServiceExportList(a.(*v1alpha1.ServiceExportList), b.(*multicluster.ServiceExportList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*multicluster.ServiceExportList)(nil), (*v1alpha1.ServiceExportList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_multicluster_ServiceExportList_To_v1alpha1_ServiceExportList(a.(*multicluster.ServiceExportList), b.(*v1alpha1.ServiceExportList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ServiceExportStatus)(nil), (*multicluster.ServiceExportStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServiceExportStatus_To_multicluster_ServiceExportStatus(a.(*v1alpha1.ServiceExportStatus), b.(*multicluster.ServiceExportStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*multicluster.ServiceExportStatus)(nil), (*v1alpha1.ServiceExportStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_multicluster_ServiceExportStatus_To_v1alpha1_ServiceExportStatus(a.(*multicluster.ServiceExportStatus), b.(*v1alpha1.ServiceExportStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ServiceImport)(nil), (*multicluster.ServiceImport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServiceImport_To_multicluster_ServiceImport(a.(*v1alpha1.ServiceImport), b.(*multicluster.ServiceImport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*multicluster.ServiceImport)(nil), (*v1alpha1.ServiceImport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_multicluster_ServiceImport_To_v1alpha1_ServiceImport(a.(*multicluster.ServiceImport), b.(*v1alpha1.ServiceImport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ServiceImportList)(nil), (*multicluster.ServiceImportList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServiceImportList_To_multicluster_ServiceImportList(a.(*v1alpha1.ServiceImportList), b.(*multicluster.ServiceImportList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*multicluster.ServiceImportList)(nil), (*v1alpha1.ServiceImportList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_multicluster_ServiceImportList_To_v1alpha1_ServiceImportList(a.(*multicluster.ServiceImportList), b.(*v1alpha1.ServiceImportList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.ServiceImportSpec)(nil), (*multicluster.ServiceImportSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServiceImportSpec_To_multicluster_ServiceImportSpec(a.(*v1alpha1.ServiceImportSpec), b.(*multicluster.ServiceImportSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*multicluster.ServiceImportSpec)(nil), (*v1alpha1.ServiceImportSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_multicluster_ServiceImportSpec_To_v1alpha1_ServiceImportSpec(a.(*multicluster.ServiceImportSpec), b.(*v1alpha1.ServiceImportSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ClusterSpec_To_multicluster_ClusterSpec(in *v1alpha1.ClusterSpec, out *multicluster.ClusterSpec, s conversion.Scope) error {
	out.Cluster = in.Cluster
	out.TopologyKeys = *(*[]string)(unsafe.Pointer(&in.TopologyKeys))
	out.PublishNotReadyAddresses = in.PublishNotReadyAddresses
	out.SessionAffinity = core.ServiceAffinity(in.SessionAffinity)
	out.SessionAffinityConfig = (*core.SessionAffinityConfig)(unsafe.Pointer(in.SessionAffinityConfig))
	return nil
}

// Convert_v1alpha1_ClusterSpec_To_multicluster_ClusterSpec is an autogenerated conversion function.
func Convert_v1alpha1_ClusterSpec_To_multicluster_ClusterSpec(in *v1alpha1.ClusterSpec, out *multicluster.ClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterSpec_To_multicluster_ClusterSpec(in, out, s)
}

func autoConvert_multicluster_ClusterSpec_To_v1alpha1_ClusterSpec(in *multicluster.ClusterSpec, out *v1alpha1.ClusterSpec, s conversion.Scope) error {
	out.Cluster = in.Cluster
	out.TopologyKeys = *(*[]string)(unsafe.Pointer(&in.TopologyKeys))
	out.PublishNotReadyAddresses = in.PublishNotReadyAddresses
	out.SessionAffinity = v1.ServiceAffinity(in.SessionAffinity)
	out.SessionAffinityConfig = (*v1.SessionAffinityConfig)(unsafe.Pointer(in.SessionAffinityConfig))
	return nil
}

// Convert_multicluster_ClusterSpec_To_v1alpha1_ClusterSpec is an autogenerated conversion function.
func Convert_multicluster_ClusterSpec_To_v1alpha1_ClusterSpec(in *multicluster.ClusterSpec, out *v1alpha1.ClusterSpec, s conversion.Scope) error {
	return autoConvert_multicluster_ClusterSpec_To_v1alpha1_ClusterSpec(in, out, s)
}

func autoConvert_v1alpha1_ServiceExport_To_multicluster_ServiceExport(in *v1alpha1.ServiceExport, out *multicluster.ServiceExport, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ServiceExportStatus_To_multicluster_ServiceExportStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ServiceExport_To_multicluster_ServiceExport is an autogenerated conversion function.
func Convert_v1alpha1_ServiceExport_To_multicluster_ServiceExport(in *v1alpha1.ServiceExport, out *multicluster.ServiceExport, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceExport_To_multicluster_ServiceExport(in, out, s)
}

func autoConvert_multicluster_ServiceExport_To_v1alpha1_ServiceExport(in *multicluster.ServiceExport, out *v1alpha1.ServiceExport, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_multicluster_ServiceExportStatus_To_v1alpha1_ServiceExportStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_multicluster_ServiceExport_To_v1alpha1_ServiceExport is an autogenerated conversion function.
func Convert_multicluster_ServiceExport_To_v1alpha1_ServiceExport(in *multicluster.ServiceExport, out *v1alpha1.ServiceExport, s conversion.Scope) error {
	return autoConvert_multicluster_ServiceExport_To_v1alpha1_ServiceExport(in, out, s)
}

func autoConvert_v1alpha1_ServiceExportCondition_To_multicluster_ServiceExportCondition(in *v1alpha1.ServiceExportCondition, out *multicluster.ServiceExportCondition, s conversion.Scope) error {
	out.Type = multicluster.ServiceExportConditionType(in.Type)
	out.Status = core.ConditionStatus(in.Status)
	out.LastTransitionTime = (*metav1.Time)(unsafe.Pointer(in.LastTransitionTime))
	out.Reason = (*string)(unsafe.Pointer(in.Reason))
	out.Message = (*string)(unsafe.Pointer(in.Message))
	return nil
}

// Convert_v1alpha1_ServiceExportCondition_To_multicluster_ServiceExportCondition is an autogenerated conversion function.
func Convert_v1alpha1_ServiceExportCondition_To_multicluster_ServiceExportCondition(in *v1alpha1.ServiceExportCondition, out *multicluster.ServiceExportCondition, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceExportCondition_To_multicluster_ServiceExportCondition(in, out, s)
}

func autoConvert_multicluster_ServiceExportCondition_To_v1alpha1_ServiceExportCondition(in *multicluster.ServiceExportCondition, out *v1alpha1.ServiceExportCondition, s conversion.Scope) error {
	out.Type = v1alpha1.ServiceExportConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	out.LastTransitionTime = (*metav1.Time)(unsafe.Pointer(in.LastTransitionTime))
	out.Reason = (*string)(unsafe.Pointer(in.Reason))
	out.Message = (*string)(unsafe.Pointer(in.Message))
	return nil
}

// Convert_multicluster_ServiceExportCondition_To_v1alpha1_ServiceExportCondition is an autogenerated conversion function.
func Convert_multicluster_ServiceExportCondition_To_v1alpha1_ServiceExportCondition(in *multicluster.ServiceExportCondition, out *v1alpha1.ServiceExportCondition, s conversion.Scope) error {
	return autoConvert_multicluster_ServiceExportCondition_To_v1alpha1_ServiceExportCondition(in, out, s)
}

func autoConvert_v1alpha1_ServiceExportList_To_multicluster_ServiceExportList(in *v1alpha1.ServiceExportList, out *multicluster.ServiceExportList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]multicluster.ServiceExport)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ServiceExportList_To_multicluster_ServiceExportList is an autogenerated conversion function.
func Convert_v1alpha1_ServiceExportList_To_multicluster_ServiceExportList(in *v1alpha1.ServiceExportList, out *multicluster.ServiceExportList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceExportList_To_multicluster_ServiceExportList(in, out, s)
}

func autoConvert_multicluster_ServiceExportList_To_v1alpha1_ServiceExportList(in *multicluster.ServiceExportList, out *v1alpha1.ServiceExportList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha1.ServiceExport)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_multicluster_ServiceExportList_To_v1alpha1_ServiceExportList is an autogenerated conversion function.
func Convert_multicluster_ServiceExportList_To_v1alpha1_ServiceExportList(in *multicluster.ServiceExportList, out *v1alpha1.ServiceExportList, s conversion.Scope) error {
	return autoConvert_multicluster_ServiceExportList_To_v1alpha1_ServiceExportList(in, out, s)
}

func autoConvert_v1alpha1_ServiceExportStatus_To_multicluster_ServiceExportStatus(in *v1alpha1.ServiceExportStatus, out *multicluster.ServiceExportStatus, s conversion.Scope) error {
	out.Conditions = *(*[]multicluster.ServiceExportCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_ServiceExportStatus_To_multicluster_ServiceExportStatus is an autogenerated conversion function.
func Convert_v1alpha1_ServiceExportStatus_To_multicluster_ServiceExportStatus(in *v1alpha1.ServiceExportStatus, out *multicluster.ServiceExportStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceExportStatus_To_multicluster_ServiceExportStatus(in, out, s)
}

func autoConvert_multicluster_ServiceExportStatus_To_v1alpha1_ServiceExportStatus(in *multicluster.ServiceExportStatus, out *v1alpha1.ServiceExportStatus, s conversion.Scope) error {
	out.Conditions = *(*[]v1alpha1.ServiceExportCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_multicluster_ServiceExportStatus_To_v1alpha1_ServiceExportStatus is an autogenerated conversion function.
func Convert_multicluster_ServiceExportStatus_To_v1alpha1_ServiceExportStatus(in *multicluster.ServiceExportStatus, out *v1alpha1.ServiceExportStatus, s conversion.Scope) error {
	return autoConvert_multicluster_ServiceExportStatus_To_v1alpha1_ServiceExportStatus(in, out, s)
}

func autoConvert_v1alpha1_ServiceImport_To_multicluster_ServiceImport(in *v1alpha1.ServiceImport, out *multicluster.ServiceImport, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ServiceImportSpec_To_multicluster_ServiceImportSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ServiceImport_To_multicluster_ServiceImport is an autogenerated conversion function.
func Convert_v1alpha1_ServiceImport_To_multicluster_ServiceImport(in *v1alpha1.ServiceImport, out *multicluster.ServiceImport, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceImport_To_multicluster_ServiceImport(in, out, s)
}

func autoConvert_multicluster_ServiceImport_To_v1alpha1_ServiceImport(in *multicluster.ServiceImport, out *v1alpha1.ServiceImport, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_multicluster_ServiceImportSpec_To_v1alpha1_ServiceImportSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_multicluster_ServiceImport_To_v1alpha1_ServiceImport is an autogenerated conversion function.
func Convert_multicluster_ServiceImport_To_v1alpha1_ServiceImport(in *multicluster.ServiceImport, out *v1alpha1.ServiceImport, s conversion.Scope) error {
	return autoConvert_multicluster_ServiceImport_To_v1alpha1_ServiceImport(in, out, s)
}

func autoConvert_v1alpha1_ServiceImportList_To_multicluster_ServiceImportList(in *v1alpha1.ServiceImportList, out *multicluster.ServiceImportList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]multicluster.ServiceImport)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ServiceImportList_To_multicluster_ServiceImportList is an autogenerated conversion function.
func Convert_v1alpha1_ServiceImportList_To_multicluster_ServiceImportList(in *v1alpha1.ServiceImportList, out *multicluster.ServiceImportList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceImportList_To_multicluster_ServiceImportList(in, out, s)
}

func autoConvert_multicluster_ServiceImportList_To_v1alpha1_ServiceImportList(in *multicluster.ServiceImportList, out *v1alpha1.ServiceImportList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1alpha1.ServiceImport)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_multicluster_ServiceImportList_To_v1alpha1_ServiceImportList is an autogenerated conversion function.
func Convert_multicluster_ServiceImportList_To_v1alpha1_ServiceImportList(in *multicluster.ServiceImportList, out *v1alpha1.ServiceImportList, s conversion.Scope) error {
	return autoConvert_multicluster_ServiceImportList_To_v1alpha1_ServiceImportList(in, out, s)
}

func autoConvert_v1alpha1_ServiceImportSpec_To_multicluster_ServiceImportSpec(in *v1alpha1.ServiceImportSpec, out *multicluster.ServiceImportSpec, s conversion.Scope) error {
	out.Ports = *(*[]core.ServicePort)(unsafe.Pointer(&in.Ports))
	out.Clusters = *(*[]multicluster.ClusterSpec)(unsafe.Pointer(&in.Clusters))
	out.IPFamily = (*core.IPFamily)(unsafe.Pointer(in.IPFamily))
	out.IP = in.IP
	return nil
}

// Convert_v1alpha1_ServiceImportSpec_To_multicluster_ServiceImportSpec is an autogenerated conversion function.
func Convert_v1alpha1_ServiceImportSpec_To_multicluster_ServiceImportSpec(in *v1alpha1.ServiceImportSpec, out *multicluster.ServiceImportSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServiceImportSpec_To_multicluster_ServiceImportSpec(in, out, s)
}

func autoConvert_multicluster_ServiceImportSpec_To_v1alpha1_ServiceImportSpec(in *multicluster.ServiceImportSpec, out *v1alpha1.ServiceImportSpec, s conversion.Scope) error {
	out.Ports = *(*[]v1.ServicePort)(unsafe.Pointer(&in.Ports))
	out.Clusters = *(*[]v1alpha1.ClusterSpec)(unsafe.Pointer(&in.Clusters))
	out.IPFamily = (*v1.IPFamily)(unsafe.Pointer(in.IPFamily))
	out.IP = in.IP
	return nil
}

// Convert_multicluster_ServiceImportSpec_To_v1alpha1_ServiceImportSpec is an autogenerated conversion function.
func Convert_multicluster_ServiceImportSpec_To_v1alpha1_ServiceImportSpec(in *multicluster.ServiceImportSpec, out *v1alpha1.ServiceImportSpec, s conversion.Scope) error {
	return autoConvert_multicluster_ServiceImportSpec_To_v1alpha1_ServiceImportSpec(in, out, s)
}
